### ISSUE TITLE
How to sign unsigned TX

### ISSUE THREAD

**Issue by WarHawk007** [monero-ecosystem/monero-javascript#10]

**Comment by woodser** [comment]
Hi WarHawk007, I have added support for [signTxs()](https://github.com/monero-ecosystem/monero-javascript/blob/23fba17da1ddae4578abe00f7a6d9f32f5ab9119/src/main/js/wallet/MoneroWallet.js#L777) and [submitTxs()](https://github.com/monero-ecosystem/monero-javascript/blob/23fba17da1ddae4578abe00f7a6d9f32f5ab9119/src/main/js/wallet/MoneroWallet.js#L787) in MoneroWalletRpc.js in master.

**Comment by woodser** [comment]
[This test](https://github.com/monero-ecosystem/monero-javascript/blob/cccb8cfb709c5d0764a96afa845e12bda1e111e6/src/test/TestMoneroWalletCommon.js#L2676) shows creating a watch-only wallet, creating unsigned txs, then signing and submitting the txs.

**Comment by WarHawk007** [comment]
Please Also update npm package

**Comment by woodser** [comment]
Done: https://www.npmjs.com/package/monero-javascript/v/0.2.4
