### ISSUE TITLE
unlockHeight Config Flag Not Working On sweepUnlocked and createTX

### ISSUE THREAD

**Issue by itsMikeLowrey** [monero-ecosystem/monero-javascript#109]
I am looking to create a transaction and store it later for broadcasting. The js docs indicate that this should be possible but it seems as if the wallet will not give me a transaction hex if the funds are locked. I have tried it with sweepUnlocked and createTX. I have my code below but do to the timing issue , the unlock issue wont show up if you run my code. Thanks for the help and let me know if you need anymore info on the bug. 

`const monerojs = require("monero-javascript");
if (monerojs.LibraryUtils.WORKER_DIST_PATH.indexOf("C:") == 0 && monerojs.LibraryUtils.WORKER_DIST_PATH.indexOf("file://") == -1)
    monerojs.LibraryUtils.WORKER_DIST_PATH = "file://"+monerojs.LibraryUtils.WORKER_DIST_PATH;
main();
async function main() {
  let walletFull = await monerojs.createWalletFull({
    networkType: "stagenet",
    password: "0",
    serverUri: "https://stagenet.xmr.ditatompel.com:443",
    restoreHeight:  1203975,
    mnemonic: 'cement square dreams glide metro moisture natural dented onslaught unmask nobody idiom lordship azure rekindle dormant wickets language snug wildly vigilant dime neutral otherwise wildly'
  });
  const isConnected = await walletFull.isConnectedToDaemon()
  console.log("wallet connection status: " + isConnected)
  await walletFull.sync(new class extends monerojs.MoneroWalletListener {
    onSyncProgress(height, startHeight, endHeight, percentDone, message) {
      console.log('percentDone: '+ percentDone)
      console.log('blockheight: ' + height)
      }
    });
  await walletFull.startSyncing(10000000);
  console.log(' ')
  const unlockedBalance = await walletFull.getUnlockedBalance()
  const blockTillFundsUnlock = await walletFull.getNumBlocksToUnlock()
  const totalBalance = await walletFull.getBalance()
  console.log('unlockedBalance: ' + unlockedBalance.toString())
  console.log('total balance:  ' + totalBalance)
  console.log('blocks for funds to unlock: ' + blockTillFundsUnlock[1])
  const tx = await walletFull.createTx({
    address: "73a4nWuvkYoYoksGurDjKZQcZkmaxLaKbbeiKzHnMmqKivrCzq5Q2JtJG1UZNZFqLPbQ3MiXCk2Q5bdwdUNSr7X9QrPubkn",
    relay: false,
    unlockHeight: 9,
    amount: '1',
    accountIndex: 0
  })
  console.log(tx)
  async function myFunctionThatCatches() {
    try {
        return await walletFull.close(true)
    } catch (e) {

    } finally {
    }
    return "Nothing found";
}
  await myFunctionThatCatches()
  process.exit();
}
`

**Comment by itsMikeLowrey** [comment]
I also tried to create the config, check that unlockheight exist. It still would not give me a transaction until the funds unlocked. 
`  const config1 = new monerojs.MoneroTxConfig({
    address: "73a4nWuvkYoYoksGurDjKZQcZkmaxLaKbbeiKzHnMmqKivrCzq5Q2JtJG1UZNZFqLPbQ3MiXCk2Q5bdwdUNSr7X9QrPubkn",
    relay: false,
    unlockHeight: 10
    // amount: '1',
    // accountIndex: 0
 });
 console.log(config1.getUnlockHeight())`

**Comment by woodser** [comment]
Inputs need to be unlocked in order to construct a tx which spends them.

Technically, it's possible to construct the tx after the inputs confirm and before they unlock, but this isn't currently supported in monero-project.

**Comment by itsMikeLowrey** [comment]
Thanks for the Response and great library!

**Comment by woodser** [comment]
Thanks. :)
