### ISSUE TITLE
Path Worker prepends file:// only in paths starting with C:

### ISSUE THREAD

**Issue by gitbraincomputing** [monero-ecosystem/monero-javascript#126]
The library works only if the project is in the root directory at c:.

original function present in monero-javascript/src/main/js/common/LibraryUtils.js
```
static _prefixWindowsPath(path) {
    if (path.indexOf("C:") == 0 && path.indexOf("file://") == -1) path = "file://" + path; // prepend C: paths with file://
    return path;
  }
```

my proposal for the fix
```
static _prefixWindowsPath(path) {
    if (/^[A-Z]:/.test(path) && path.indexOf("file://") == -1) path = "file://" + path; // prepend C: paths with file://
    return path;
  }
```
this way it is possible to have the project and the node_modules folder in a disk drive other than c, as happened in my thing.

**Comment by woodser** [comment]
Nice, thanks. It will be in the next release expected within a few days.

**Comment by woodser** [comment]
This is now supported in the v0.8.0 release. Thanks again.

**Comment by woodser** [comment]
Closing as resolved. Please let me know if you see any issue. Thanks.
