### ISSUE TITLE
Get error when running "Creating a Node.js Application"

### ISSUE THREAD

**Issue by wrightpt** [monero-ecosystem/monero-javascript#129]
Seems to be around:

> monero_wallet_keys.wasm',
> 
>     code: 'ERR_INVALID_URL'

Can anyone replicate?

thanks

`const monerojs = require("monero-javascript");

main();
async function main() {
  
  // create a random keys-only (offline) stagenet wallet
  let walletKeys = await monerojs.createWalletKeys({networkType: "stagenet", language: "English"});

  // print wallet attributes
  console.log("Seed phrase: " + await walletKeys.getSeed());
  console.log("Address: " + await walletKeys.getAddress(0,0)); // get address of account 0, subaddress 0
  console.log("Spend key: " + await walletKeys.getPrivateSpendKey());
  console.log("View key: " + await walletKeys.getPrivateViewKey());
}`

Error:

> > TypeError: Failed to parse URL from /home/p/Documents/offline_generator/node_modules/monero-javascript/dist/monero_wallet_keys.wasm
>     at Object.fetch (node:internal/deps/undici/undici:11457:11) {
>   [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
>       at new NodeError (node:internal/errors:399:5)
>       at new URL (node:internal/url:560:13)
>       at new Request (node:internal/deps/undici/undici:7041:25)
>       at fetch2 (node:internal/deps/undici/undici:10598:25)
>       at Object.fetch (node:internal/deps/undici/undici:11455:18)
>       at fetch (node:internal/process/pre_execution:230:25)
>       at instantiateAsync (/home/p/Documents/offline_generator/node_modules/monero-javascript/dist/monero_wallet_keys.js:9:14342)
>       at createWasm (/home/p/Documents/offline_generator/node_modules/monero-javascript/dist/monero_wallet_keys.js:9:14952)
>       at /home/p/Documents/offline_generator/node_modules/monero-javascript/dist/monero_wallet_keys.js:9:102270
>       at LibraryUtils.loadKeysModule (/home/p/Documents/offline_generator/node_modules/monero-javascript/src/main/js/common/LibraryUtils.js:74:78)
>       at MoneroWalletKeys._createWalletRandom (/home/p/Documents/offline_generator/node_modules/monero-javascript/src/main/js/wallet/MoneroWalletKeys.js:71:37)
>       at MoneroWalletKeys.createWallet (/home/p/Documents/offline_generator/node_modules/monero-javascript/src/main/js/wallet/MoneroWalletKeys.js:58:34)
>       at module.exports.createWalletKeys (/home/p/Documents/offline_generator/node_modules/monero-javascript/index.js:286:87)
>       at main (/home/p/Documents/offline_generator/file.js:7:35)
>       at Object.<anonymous> (/home/p/Documents/offline_generator/file.js:3:1)
>       at Module._compile (node:internal/modules/cjs/loader:1254:14)
>       at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
>       at Module.load (node:internal/modules/cjs/loader:1117:32)
>       at Module._load (node:internal/modules/cjs/loader:958:12)
>       at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>       at node:internal/main/run_main_module:23:47 {
>     input: '/home/p/Documents/offline_generator/node_modules/monero-javascript/dist/monero_wallet_keys.wasm',
>     code: 'ERR_INVALID_URL'
>   }
> }
>

**Comment by woodser** [comment]
That sample code runs for me as written.

The library current requires Node 16 LTS. Are you using 17+?

**Comment by wrightpt** [comment]
This fixed it. Thank you

**Comment by woodser** [comment]
Alternatively you can run LTS 18 and with the `--no-experimental-fetch` flag.
