### ISSUE TITLE
missing load_txt_records_from_dns 

### ISSUE THREAD

**Issue by hungminhtran** [monero-ecosystem/monero-javascript#34]
I try to create a new transaction but got this error:

missing function: _ZN5tools9dns_utils25load_txt_records_from_dnsERNSt3__26vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEERKSA_

version: "monero-javascript": "^0.4.0"
nodejs version: 10.15.3

**Comment by woodser** [comment]
Fixed in release 0.4.1.  Thanks for pointing out this issue!
