### ISSUE TITLE
Getting 401 error: unauthorized when using createWalletWasm() with local node

### ISSUE THREAD

**Issue by hundehausen** [monero-ecosystem/monero-javascript#39]
**versions**:
monero-javascript 0.4.3
monerod v0.16.0.3
node v14.9.0
npm 6.14.8
react 16.13.1
babel core 7.11.4
webpack 4.44.1
webpack-dev-server 3.11.0

**usage**:
`./monerod --stagenet --rpc-login superuser:abctesting123 --rpc-access-control-origins http://localhost:8080`

then I start the webpack-dev-server on http://localhost:8080

**relevant code**:
```
const monerojs = require("monero-javascript");

let walletRpc = new monerojs.MoneroRpcConnection({
  //uri: "http://stagenet.community.xmr.to:38081",
  uri: "http://localhost:38081",
  username: "superuser",
  password: "abctesting123",
  rejectUnauthorized: false, // e.g. local development
});

export async function createWallet(lang = "English") {
  console.log("Creating new wallet");
  let walletWasm = await monerojs.createWalletWasm({
    networkType: "stagenet",
    language: lang,
    password: "pass123",
    server: walletRpc,
  });
  return walletWasm;
}
```

**error**:
on host system macOS 10.15.6
for both Firefox 80.0.1 and Brave 1.13.82 (Chromium 85.0.4183.83)
in the browser console:
```
XHRPOSThttp://localhost:38081/json_rpc
[HTTP/1.1 401 Unauthorized 0ms]
```

If I try to use the JSON RPC with Postman I get it to work, but not with monero-javascript and the WASM Wallet in the browser. Am I doing something wrong?

Thanks!

**Comment by woodser** [comment]
> ```
> let walletRpc = new monerojs.MoneroRpcConnection({
>   //uri: "http://stagenet.community.xmr.to:38081",
>   uri: "http://localhost:38081",
>   username: "superuser",
>   password: "abctesting123",
>   rejectUnauthorized: false, // e.g. local development
> });
> ```

The uri, username, and password here are for the monero-wallet-rpc server, not the daemon started with `./monerod`.  monero-wallet-rpc is configured with a daemon endpoint on startup.

> ```
> let walletWasm = await monerojs.createWalletWasm({
>     networkType: "stagenet",
>     language: lang,
>     password: "pass123",
>     server: walletRpc,
>   });
> ```

The wasm wallet doesn't use monero-wallet-rpc.  It communicates directly with a daemon, so you probably want:

```
let walletWasm = await monerojs.createWalletWasm({
    networkType: "stagenet",
    language: lang,
    password: "pass123",
    serverUri: "http://localhost:38081",
    serverUsername: "superuser",
    serverPassword: "abctesting123"
  });
```

**Comment by hundehausen** [comment]
Hey woodser,

thanks for your response.
I tried changing it to 

let walletWasm = await monerojs.createWalletWasm({
    networkType: "stagenet",
    language: lang,
    password: "pass123",
    serverUri: "http://localhost:38081",
    serverUsername: "superuser",
    serverPassword: "abctesting123",
  });

But I still get the same error with 401 unauthorized.

**Comment by woodser** [comment]
Sorry I misread your issue at first.  I don't see anything wrong with your configuration.

A 401 authentication challenge is expected on each request to the daemon.  A follow-up request should then succeed with 200.  Are they not?

You might look at [this branch](https://github.com/woodser/monerostresstester.com/tree/stress_tester_v2) in the monerostresstester repo which uses a similar setup as you (react, webpack-dev-server, etc) and is tested working in the browser with a daemon.

**Comment by hundehausen** [comment]
Thanks it works now! As you expected, I still get lots of 401 errors. Why is it designed like that?
Thanks for showing uns the branch of your monerostresstester repo. It will help us a lot.

How do I use a remote node in a WASM wallet without getting the CORS errors?

**Comment by woodser** [comment]
> I still get lots of 401 errors. Why is it designed like that?

Per [HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication), the server responds to a client request with a 401 unauthorized and information for the client to authenticate in a subsequent request.

> How do I use a remote node in a WASM wallet without getting the CORS errors?

The daemon needs to be configured to allow clients from a specific origin (wildcard isn't supported last I knew).

**Comment by hundehausen** [comment]
Okay thank you! monero-javascript is great. We are happy to have the ability to use a monero WASM wallet in the browser.
