### ISSUE TITLE
Build with latest emsdk leads to runtime error in monero_core.wasm

### ISSUE THREAD

**Issue by MartyHav** [monero-ecosystem/monero-javascript#40]
When building wasm via emsdk 2.0.4, the creation of a random wallet ( and I think of any wallet ) will throw a Segmentation fault. monero_core_keys seems still to work. Going back to emsdk 1.40 resolves this issue.
No idea at which version this error starts to occur. 
The changelog ( 2.0.4 ) states: 

> Stop including `malloc` and `free` by default. If you need access to them from
>   JS, you must export them manually using
>   `-s EXPORTED_FUNCTIONS=['_malloc', ..]`.

https://emscripten.org/docs/introducing_emscripten/release_notes.html#changelog

I did try that without success.

**Comment by woodser** [comment]
The problem seems to be related to different Asyncify behavior starting in 2.0.3.

https://github.com/emscripten-core/emscripten/issues/12295

**Comment by woodser** [comment]
This issue is resolved in the 2.0.5 release of emsdk and emscripten.
