### ISSUE TITLE
Hardcoded path to MoneroWebWorker.dist.js

### ISSUE THREAD

**Issue by mghny** [monero-ecosystem/monero-javascript#41]
Good Evening,

currently I am creating an web-application based on your [sample app](https://github.com/woodser/xmr-sample-app). With the given instructions its super easy to start the application and work with the library.

But when I extend the source with a new page lying in a subdirectory, the library tries to load the "MoneroWebWorker.dist.js" worker code from this directory e.g.

Does work:
```html
<!-- /index.html -->
<script type="text/javascript" src="/sample_code.dist.js"></script>
```
Result: `GET http://localhost:9100/subfolder/MoneroWebWorker.dist.js 200 OK`

Does not work:
```html
<!-- /subdirectory/index.html -->
<script type="text/javascript" src="/sample_code.dist.js"></script>
```
Result:  `GET http://localhost:9100/subfolder/MoneroWebWorker.dist.js 404 (File not found)`

A quick look at the source code made the problem obvious:

https://github.com/monero-ecosystem/monero-javascript/blob/307f09f1627ed16e967599887e6dd9a781440196/src/main/js/common/LibraryUtils.js#L133

I don't know whether this script needs to be referenced relative or not. Are there any plans to change this behaviour? Right now I'm forking the project and specifying the absolute path by hand but this seems to be a bit of an overkill for this small change.

Thank you for your attention to this matter.

**Comment by woodser** [comment]
Ah good observation.  That line can be changed to hardcode to root:

`LibraryUtils.WORKER = new Worker("/MoneroWebWorker.dist.js");`

Unless it would be of value to specify the worker path?

**Comment by mghny** [comment]
That's what I did on my local copy.

Specifying a value would be okay to...but right now I can't imagine how to properly set/exchange it with the static LibraryUtils class. Would you suggest something like `LibraryUtils.WORKER_DIST_PATH` with the default value of `/MoneroWebWorker.dist.js`?

**Comment by woodser** [comment]
Fixed in https://github.com/monero-ecosystem/monero-javascript/commit/6778867de7d17524d89ae801487bce32a64a8c48

**Comment by mghny** [comment]
Thank you very much! I guess this can be closed now
