### ISSUE TITLE
Sweep all, Transfer_split and Finalize multisig not implemented

### ISSUE THREAD

**Issue by grcasanova** [monero-ecosystem/monero-javascript#44]
Are _sweep_all_, _transfer_split_ and _finalize_multisig_ RPC functions implemented yet?

**Comment by woodser** [comment]
Yes, but monero-javascript's terminology is slightly different than monero-wallet-rpc (supported by monero-project's wallet2).

For `sweep_all`, call [MoneroWallet.sweepUnlocked()](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#sweepUnlocked) specifying an account and subaddress(es) if desired.

For `transfer_split`, call [MoneroWallet.createTxs()](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#createTxs) which will create more than one tx if necessary.

For `finalize_multisig`, call [MoneroWallet.exchangeMultisigKeys()](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#exchangeMultisigKeys) which is just the generalized form for all M/N wallets where M != N (see [this test](https://github.com/monero-ecosystem/monero-javascript/blob/a76648416afcee1631e05ff916fcf29c5345136c/src/test/TestMoneroWalletCommon.js#L3657) for a usage example).
