### ISSUE TITLE
Vue.js integration

### ISSUE THREAD

**Issue by omurad** [monero-ecosystem/monero-javascript#47]
Installation
`npm install monero-javascript --save`

Test Code
```
<template>
	<h5>Blockheight: {{ height }}</h5>
</template>

<script>
import monerojs from 'monero-javascript'

export default {
	name: "Test",
	data(){
		return {
			height: 0
		}
	},
	async mounted() {
		let daemon = monerojs.connectToDaemonRpc("http://1.2.3.4:18089")
		let height = await daemon.getHeight()
		console.log(height)
		this.height = height
	}
}
</script>
```

Browser console error
`Loading Worker from “http://localhost:8080/MoneroWebWorker.dist.js” was blocked because of a disallowed MIME type (“text/html”).`

Not sure how to go about resolving this error. Are any additional steps necessary to integrate `monero-javascript` with Vue.js?

**Comment by woodser** [comment]
The problem is likely that monero-javascript/dist/MoneroWebWorker.js needs copied to your application's browser build directory.  It should be as easy as copying this file to the root of your built web app.

I've added instructions and a more informative error message when MoneroWebWorker.js fails to make this more clear.

**Comment by woodser** [comment]
b6fac9f4f8c5851868f5bc32349f985ad9c9466d

**Comment by woodser** [comment]
This [webpack config](https://github.com/woodser/monerostresstester.com/blob/8378dc4283005ad831e8f45f5ec1dae1ae9b66b8/webpack.config.js#L83) copies node_modules/monero-javascript/dist to a target build directory automatically.

**Comment by omurad** [comment]
That seems to fix the issue.

I appreciate your help and prompt response.

How does the GitHub to NPM integration work? Will these changes be immediately reflected in the NPM package?

**Comment by woodser** [comment]
FYI, monero-javascript-v0.5.0 is released which contains improved error messages from this issue.

The update has some breaking changes, specifically:
- `await` should now be used with `monerojs.connectToDaemonRpc()` and `monerojs.connectToWalletRpc()`
- "MoneroWalletWasm" is renamed to "MoneroWalletFull"
- Files built to ./dist have been renamed to "monero_wallet_full*", "monero_wallet_keys*", and "monero_web_worker*"

[Release notes](https://github.com/monero-ecosystem/monero-javascript/releases/tag/v0.5.0)
