### ISSUE TITLE
404 not found http://localhost:8080/MoneroWebWorker.dist.js

### ISSUE THREAD

**Issue by hundehausen** [monero-ecosystem/monero-javascript#48]
Hi woodser, 

it's hundehausen from TipXMR.
We upgraded to v0.5.0 and now we see some errors like:
404 not found http://localhost:8080/MoneroWebWorker.dist.js

<img width="811" alt="Bildschirmfoto 2021-01-25 um 19 53 48" src="https://user-images.githubusercontent.com/25672277/105752039-1a178d80-5f47-11eb-8a48-33a3d61520dd.png">

Did something change that affects imports?

Thank you

**Comment by woodser** [comment]
MoneroWebWorker.dist.js was renamed to monero_web_worker.dist.js for consistency with the other files built to ./dist.  Nothing should be referencing MoneroWebWorker.dist.js anymore.  Perhaps the browser needs hard refreshed to use the new file name, or if you build the WASM files yourself, perhaps they need rebuilt?

**Comment by hundehausen** [comment]
Hey,
I already tested with a fresh browser install and all cache cleared. We don't build the WASM files ourselves, we just copy the files from monero-javascript dist folder to [our dist folder](https://github.com/hundehausen/tipxmr/tree/dockerize/dist).

**Comment by woodser** [comment]
I searched the current dist files and source just to be sure there are no old references to MoneroWebWorker.dist.js.  

Your web application is attempting to use the old path suggesting it's not built with monero-javascript-v0.5.0.  The branch you pointed me to is using monero-javascript-v0.4.5 in package.json.  The web application should use the correct, updated path after:

1. Updating package.json to monero-javascript-v0.5.0
2. `npm install`
3. Rebuilding and starting the web application

**Comment by hundehausen** [comment]
I am pretty sure I use v0.5.0 in the branch _dockerize_ and I also checked the monero-javascript/package.json in the node modules folder. It is v0.5.0. I downgraded webpack to version 4.44.2 and ran "npm run build". I get the following error:
`
ERROR in ../node_modules/monero-javascript/src/main/js/wallet/MoneroWalletRpc.js
Module not found: Error: Can't resolve 'child_process' in '/Users/grischadaum/Coding/TipDocker/projects/tipxmr-frontend/node_modules/monero-javascript/src/main/js/wallet'
 @ ../node_modules/monero-javascript/src/main/js/wallet/MoneroWalletRpc.js 116:19-43
 @ ../node_modules/monero-javascript/index.js
 @ ./libs/monero.js`

**Comment by hundehausen** [comment]
Does [this file](https://github.com/monero-ecosystem/monero-javascript/blob/master/src/main/js/common/MoneroWebWorker.js) need to be renamed?

**Comment by woodser** [comment]
That error is a good sign since it means the web app is building with v0.5.0.

"child_process" needs added to the node.js exclusion list in the webpack configuration [here](https://github.com/hundehausen/tipxmr/blob/eadac26477aaa73c3044000ceaa363672abcea5a/webpack.config.js#L61)

> Does [this file](https://github.com/monero-ecosystem/monero-javascript/blob/master/src/main/js/common/MoneroWebWorker.js) need to be renamed?

No because it's a source file using the camelcase convention, whereas only the built files in ./dist use underscores.

**Comment by hundehausen** [comment]
Thank you that helped to remove the build errors related to monero. I still get other errors regarding tailwind css.
I still get the 
404 not found http://localhost:8080/MoneroWebWorker.dist.js
error. Why do I have to build the project? I can not remember doing this earlier. Sorry for being such a noob :D

**Comment by woodser** [comment]
When `npm start` is called, the web app is built automatically to a directory then hosted by a server to access in a browser.  In your case, this directory is ./dist per your webpack.config.js.

Something in your ./dist directory must still reference MoneroWebWorker.dist.js.  This can be confirmed by running `cd ./dist && grep -rni "MoneroWebWorker.dist.js" *` -- if any output is generated it's using old build assets.

This would suggest the web app isn't correctly building, updating ./dist, and starting with `npm start`.

You can try deleting the ./dist directory to ensure the web app is only using the most up-to-date build, then `npm start`.  This should resolve the error accessing MoneroWebWorker.dist.js.

I tried to build your current dockerize branch but I get a compile error:

```
ERROR in ./styles.css (../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/dist/cjs.js??ref--6-2!./styles.css)
Module build failed (from ../node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'config'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
    at validate (/Users/woodser/git/tipxmr/node_modules/postcss-loader/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.loader (/Users/woodser/git/tipxmr/node_modules/postcss-loader/dist/index.js:43:29)
 @ ./styles.css 2:26-153 53:4-74:5 56:18-145
 @ ./index.js

ERROR in ./components/Loading.css (../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/dist/cjs.js??ref--6-2!./components/Loading.css)
Module build failed (from ../node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'config'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
    at validate (/Users/woodser/git/tipxmr/node_modules/postcss-loader/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.loader (/Users/woodser/git/tipxmr/node_modules/postcss-loader/dist/index.js:43:29)
 @ ./components/Loading.css 2:26-160 53:4-74:5 56:18-152
 @ ./components/Loading.js
 @ ./components/index.js
 @ ./App.js
 @ ./index.js
```

**Comment by hundehausen** [comment]
Thank you woodser. I found the problem. I dockerized the whole project and I did not realize, that I have to rebuild the docker image of the frontend to update the node_modules. So I have to find a way, that the docker container doesn't install the modules inside the container rather than mapping the node_modules folder from external. Sorry for the issue 😅

**Comment by woodser** [comment]
Glad to hear it.
