### ISSUE TITLE
Disable debug messages

### ISSUE THREAD

**Issue by xrv0** [monero-ecosystem/monero-javascript#52]
I'm integrating monero-javascript into my most recent project and it's working great so far.
However these debug sync messages are spamming my logs. Is it possible to disable them?

Example:
```
Heap resize call from 16777216 to 20185088 took 0.09554499387741089 msecs. Success: true
Heap resize call from 20185088 to 24248320 took 0.0572359561920166 msecs. Success: true
Heap resize call from 24248320 to 29097984 took 0.3719410300254822 msecs. Success: true
```

**Comment by xrv0** [comment]
or
`Background synchronizing in-memory wallet`

**Comment by xrv0** [comment]
Thanks for the quick fix.
Could you also push the update to npm, if you don't mind.

**Comment by woodser** [comment]
Yes it will be part of the next release, targeting a few days or less.

Logging will be disabled by default with add1bb5a19d7c0443ab9fb59f68be9d196ab4c41 and can be re-enabled or adjusted with `await LibraryUtils.setLogLevel(level)`.

**Comment by xrv0** [comment]
Great! Thank you

**Comment by woodser** [comment]
Sorry for the delay.  monero-javascript 0.5.3 is published now.

**Comment by hundehausen** [comment]
Hey woodser I get a error message in my console when I want to open a wallet:
Error: Method 'setLogLevel' is not registered with worker
Is it related to the new function?

**Comment by woodser** [comment]
> Hey woodser I get a error message in my console when I want to open a wallet:
> Error: Method 'setLogLevel' is not registered with worker
> Is it related to the new function?

Yes, probably.  `setLogLevel()` was added to [the web worker](https://github.com/monero-ecosystem/monero-javascript/blob/79522ba818dff61652e8b2be01e16ab54baa5015/src/main/js/common/MoneroWebWorker.js#L58) in https://github.com/monero-ecosystem/monero-javascript/commit/add1bb5a19d7c0443ab9fb59f68be9d196ab4c41.  Is monero_web_worker.js updated in your distribution folder?

**Comment by hundehausen** [comment]
Thanks, that fixed it.

**Comment by woodser** [comment]
Closing as resolved.
