### ISSUE TITLE
WASM wallet syncing leads to high latency in socket based application 

### ISSUE THREAD

**Issue by xrv0** [monero-ecosystem/monero-javascript#53]
I'm not sure if this is specific to monero-javascript or applies to all projects which utilize CPU demanding webassembly bindings.
I'm developing a socket based application and latency is critical. When the full wallet syncs in the background CPU usage spikes from 1% to over 30% which leads to other IO operations being delayed by multiple seconds. I mitigated this by using the wallet-rpc therefore offloading the intense processing to a separate process. It works fine but introduces extra complexity.
Is this to be expected or am I doing something wrong?

**Comment by woodser** [comment]
The WASM file runs single-threaded which blocks the main thread while syncing unless offloaded e.g. to a web worker.

I think this is to be expected given the intensive operations running single-threaded in a VM.

I'm not aware of specific performance bottlenecks or opportunities for improvement in the WASM binding except possibly to build a multithreaded version which runs in some environments (help welcome - should mostly be a matter of configuration).

If performance is critical, I recommend using either an external monero-wallet-rpc server to offload wallet function or using [native Java JNI bindings](https://github.com/monero-ecosystem/monero-java#building-jni-shared-libraries-from-source) which run multithreaded with near-native performance.

**Comment by MartyHav** [comment]
for node applications we managed to reuse the bundled web worker for worker threads in node. 
This tiny lib fills the gap between worker threads and web worker api: https://github.com/developit/web-worker to make MoneroWebworker work in worker threads. Nodes main thread is not blocked anymore. I can do a PR if there is an interest.

**Comment by woodser** [comment]
> I can do a PR if there is an interest.

That would be great.  Thanks!

**Comment by xrv0** [comment]
That would be very helpful. Thanks

**Comment by MartyHav** [comment]
yes, will prepare a PR.

**Comment by woodser** [comment]
Worker support was added for node with 895fd72a1c77a9dc19df309f9678faa00144a9fc and b87d4396d385298bf898428b3998890acd5ba151.

**Comment by woodser** [comment]
Closing this issue as resolved with the release of v0.5.4 which runs the wallet and daemon in a proxy worker on node by default.

Thanks @MartyHav for the improvement.
