### ISSUE TITLE
Create new address for account?

### ISSUE THREAD

**Issue by tgbv** [monero-ecosystem/monero-javascript#57]
Is there a way to create a new subaddress for an account? I don't see any method listed in `/src/main/js/wallet/model/MoneroAccount.js`

**Comment by trasherdk** [comment]
You are looking for [MoneroSubaddress.js](https://github.com/monero-ecosystem/monero-javascript/blob/master/src/main/js/wallet/model/MoneroSubaddress.js)

**Comment by woodser** [comment]
You can use [wallet.createSubaddress(accountIdx, label)](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#createSubaddress) which creates and returns a subaddress within the specified account.

**Comment by trasherdk** [comment]
Nice docs BTW. Maybe I should check that out. Like RTFM kinda thing :smile:

**Comment by woodser** [comment]
> Nice docs BTW. Maybe I should check that out. Like RTFM kinda thing 😄

Thanks! :)

**Comment by tgbv** [comment]
Noted. Wouldn't be great to create a subaddress from `MoneroAccount` as well?

**Comment by tgbv** [comment]
Would a PR be accepted?

**Comment by woodser** [comment]
Sure.

**Comment by tgbv** [comment]
Not adding a PR as I believe it breaks the paradigm of the library.
