### ISSUE TITLE
Webpack dependency error 

### ISSUE THREAD

**Issue by jeffro256** [monero-ecosystem/monero-javascript#64]
While trying to run `npm install -D webpack-cli`, I got the following error:

    npm WARN old lockfile 
    npm WARN old lockfile The package-lock.json file was created with an old version of npm,
    npm WARN old lockfile so supplemental metadata must be fetched from the registry.
    npm WARN old lockfile 
    npm WARN old lockfile This is a one-time fix-up, please be patient...
    npm WARN old lockfile 
    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR! 
    npm ERR! While resolving: monero-javascript@0.5.4
    npm ERR! Found: webpack@5.51.1
    npm ERR! node_modules/webpack
    npm ERR!   dev webpack@"^5.50.0" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! peer webpack@"4.x.x" from webpack-cli@3.3.12
    npm ERR! node_modules/webpack-cli
    npm ERR!   dev webpack-cli@"^3.3.12" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR! 
    npm ERR! See /home/jerf/.npm/eresolve-report.txt for a full report.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/jerf/.npm/_logs/2021-08-30T17_17_31_741Z-debug.lo

This was on commit 14a82fae90dca291e7eb74e37bf9eb0bf96d1c79.

**Comment by woodser** [comment]
a96983629da10961571b89ff50f89b6d98b3ddf0 ought to fix the issue and is committed to master.

I needed to update my npm.

**Comment by jeffro256** [comment]
Hmm, I pulled the new commit, and it still doesn't work. Does it work for you?

**Comment by trasherdk** [comment]
Bump `webpack-cli` to `4.8.0` and related deps latest should fix that one.

**Comment by woodser** [comment]
> Thanks for responding! I pulled the new commit, and it still doesn't work. Does it work for you?

No actually, I had the same error running `npm install -D webpack-cli`.

But @trasherdk's suggestion worked by updating webpack-cli to 4.8.0. Resolved by https://github.com/monero-ecosystem/monero-javascript/pull/65

**Comment by jeffro256** [comment]
Okay we're making progress, cause now I've got a new error. Go easy on me if I'm just being a noob, Ithis is my first experience with webpack ;). When I run the command `npx webpack` I get this message:(I replaced the actual root folder name on my system with a placeholder):


    assets by status 0 bytes [cached] 1 asset

    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value.
    Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

    ERROR in main
    Module not found: Error: Can't resolve './src' in '<THE REPO ROOT DIRECTORY>'
    resolve './src' in '<THE REPO ROOT DIRECTORY>'
      using description file: <THE REPO ROOT DIRECTORY>/package.json (relative path: .)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: <THE REPO ROOT DIRECTORY>/package.json (relative path: ./src)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            <THE REPO ROOT DIRECTORY>/src is not a file
          .js
            Field 'browser' doesn't contain a valid alias configuration
            <THE REPO ROOT DIRECTORY>/src.js doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            <THE REPO ROOT DIRECTORY>/src.json doesn't exist
          .wasm
            Field 'browser' doesn't contain a valid alias configuration
            <THE REPO ROOT DIRECTORY>/src.wasm doesn't exist
          as directory
            existing directory <THE REPO ROOT DIRECTORY>/src
              using description file: <THE REPO ROOT DIRECTORY>/package.json (relative path: ./src)
                using path: <THE REPO ROOT DIRECTORY>/src/index
                  using description file: <THE REPO ROOT DIRECTORY>/package.json (relative path: ./src/index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      <THE REPO ROOT DIRECTORY>/src/index doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      <THE REPO ROOT DIRECTORY>/src/index.js doesn't exist
                    .json
                      Field 'browser' doesn't contain a valid alias configuration
                      <THE REPO ROOT DIRECTORY>/src/index.json doesn't exist
                    .wasm
                      Field 'browser' doesn't contain a valid alias configuration
                      <THE REPO ROOT DIRECTORY>/src/index.wasm doesn't exist

**Comment by woodser** [comment]
I get the same error running `npx webpack`. But why run this command?

**Comment by jeffro256** [comment]
Sorry that's how I assumed to build webpack for this repo. Are there any instructions on how to do this? Thanks!

**Comment by jeffro256** [comment]
Thanks for the help! Note: I get the same error for `npm install -D webpack`, but I don't thinks it's really relevant. I think I now understand how to make a static build. One more question, unrelated: is their a way to get the `keysData` and the `cacheData` from a `MoneroWalletKeys` WASM object?

**Comment by woodser** [comment]
> One more question, unrelated: is their a way to get the keysData and the cacheData from a MoneroWalletKeys WASM object?

No, because a keys-only wallet has no state data; everything is deterministically derived from the input keys.

**Comment by jeffro256** [comment]
Hmm, that's what I thought. Is there then a way to get a stream output from `MoneroWalletFull` instead of saving it to a path? I ask all these questions because I want a full wallet with the sync/cache data, but I don't want to save it directly to a file system. Thanks so much for your help, and sorry for the spam.

**Comment by woodser** [comment]
> Is there then a way to get a stream output from MoneroWalletFull instead of saving it to a path? 

Yes, with [wallet.getData()](https://moneroecosystem.org/monero-javascript/MoneroWalletFull.html#getData):

`let data = await wallet.getData(); // data[0] is the keys DataView, data[1] is the cache DataView`

> Thanks so much for your help, and sorry for the spam.

No problem at all.

**Comment by jeffro256** [comment]
Awesome! That is exactly what I was looking for, thank you! I can't believe I missed that...
