### ISSUE TITLE
[feature request] make integrated addresses for non wallet addresses

### ISSUE THREAD

**Issue by spirobel** [monero-ecosystem/monero-javascript#68]
As discussed in the monero dev matrix channel it would be nice to have a  way to create an integrated address that is not tied to the currently opened wallet.  getIntegratedAddress(paymentId) on MoneroWalletFull is currently the only option to do this if we dont want to have an wallet rpc server. 
If there is anything I can do to assist that effort let me know!

**Comment by woodser** [comment]
You can now call `MoneroUtils.getIntegratedAddress(networkType, address, paymentId)` with the monero-javascript-v0.5.9 release (commit 022fc637b49546d2f80f545406c6fced452f3b63).
