### ISSUE TITLE
Support HTTPS.

### ISSUE THREAD

**Issue by tw1t611** [monero-ecosystem/monero-javascript#7]
HTTPS seams not supported.
```js
  let walletRpc = new MoneroWalletRpc(
    "https://x.x"
  )
  await walletRpc.openWallet("x", "x")
```
Error:
```bash
(node:12037) UnhandledPromiseRejectionWarning: Error: RequestError: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:" at MoneroRpcConnection.sendJsonRequest (/home/user/Projects/jointed.gitlab.io/docker/node_modules/monero-javascript/src/main/js/rpc/MoneroRpcConnection.js:124:18)
```

It is possible to connect to monero-wallet-rpc over https with curl.
```bash
curl -X POST https://x.x/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"open_wallet","params":{"filename":"x","password":"x"}}' -H 'Content-Type: application/json'
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
  }
}
```

**Comment by woodser** [comment]
I have committed SSL support to master to support HTTPS.

To enable SSL, monero-wallet-rpc must be started with `--rpc-ssl enabled`.  See https://github.com/monero-project/monero/pull/4852 for all startup options.

Unless specified, monero-wallet-rpc generates a temporary self-signed certificate.  For the client to accept self-signed certificates, MoneroWalletRpc must be constructed with `rejectUnauthorized: false`.  This configuration is subject to MITM attacks so is only suitable for testing.

**Comment by tw1t611** [comment]
That was fast :). It did just work, thank you very much.
