### ISSUE TITLE
Cannot sign transaction offline with the example - https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/view_only_offline.md

### ISSUE THREAD

**Issue by will-yijinin** [monero-ecosystem/monero-javascript#70]
To sign a transaction offiline, I follow the code from the doc: `https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/view_only_offline.md`.
```
let viewOnlyWallet = await connectToWalletRpc("http://localhost:18082");
await viewOnlyWallet.sync();
    
// export outputs from view-only wallet
let outputsHex = await viewOnlyWallet.exportOutputs();
console.log(outputsHex)

// create offline wallet
let offlineWallet = await createWalletFull({
     networkType: MoneroNetworkType.MAINNET,
     privateSpendKey,
     primaryAddress: from,
     password: "password",
});

// import outputs to offline wallet
await offlineWallet.importOutputs(outputsHex);
// prints`4d6f6e65726f206f7574707574206578706f7274046bf1054864f10b1ba7fbe20898ad13e1a3a3c6dcc78d9ac9e8ec15bca8cc1198c50092d27077d6d678b442629e9cf229fe2beaceb7186cd9ea1eef561aac25973f3ad55431351c805c0dc9376f49c58b7fb2b4487d8143b725269495ffa9cadbe36a8d7ce3982cce2f1006fcea60c432c72e2acedeaecf4f64c59fa2aa996d110d296dddfeade796b80306`

// export key images from offline wallet
let keyImages = await offlineWallet.exportKeyImages();
console.log(JSON.stringify(keyImages))
// prints an empty array []

// import key images to view-only wallet
await viewOnlyWallet.importKeyImages(keyImages);
        
// create unsigned tx using view-only wallet
const unsignedTx = await viewOnlyWallet.createTx({
     accountIndex: 0,
     address: to,
     amount,
});

console.log(unsignedTx.getTxSet())
// prints MoneroTxSet {
      state: {
        multisigTxHex: undefined,
        unsignedTxHex: undefined,
        signedTxHex: undefined,
        txs: [ [MoneroTxWallet] ]
      }
    }

// describe unsigned tx set to confirm details
const describedTxSet = await offlineWallet.describeTxSet(unsignedTx.getTxSet());
```
The last line above throws an error: `no txset provided`. But I suppose it's already wrong at line`console.log(JSON.stringify(keyImages))` when it prints an empty array [].

**Comment by woodser** [comment]
Please first ensure it works using a mnemonic per the documentation, e.g.:

```
// create offline wallet
let offlineWallet = await monerojs.createWalletFull({
  path: "my_offline_wallet",
  networkType: "stagenet",
  mnemonic: "spying swept ashtray going hence jester swagger cease spying unusual..."
});
```

Then you can try using a private spend key instead, but it should be provided like:

```
// create offline wallet
let offlineWallet = await createWalletFull({
     networkType: MoneroNetworkType.MAINNET,
     privateSpendKey: privateSpendKey // needs defined like `privateSpendKey: ...`
     primaryAddress: from,
     password: "password",
});
```

I don't recall if the private spend key works instead of mnemonic.

**Comment by will-yijinin** [comment]
It is a different question. It has nothing to do with wallet generation. This questions asks that following steps from the example, https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/view_only_offline.md,
It cannot generate a transaction and throws error `no txset provided`

**Comment by woodser** [comment]
If the step to create the wallet is wrong (it is), it will cause the other issues you're seeing, because the offline wallet is based on a different seed than the view-only wallet.

**Comment by will-yijinin** [comment]
From the doc, it doesn't show that the offline wallet and the view-only wallet must be derived from the same mnemonic words or private key. From the doc I thought the view-only wallet and the offline wallet are completely separated entities.

**Comment by woodser** [comment]
Ah, no, the offline and view-only wallets must be for the same wallet in order to send/receive without exposing the private key to an internet connected device.
