### ISSUE TITLE
Make MoneroUtils run in the worker context

### ISSUE THREAD

**Issue by onionltd** [monero-ecosystem/monero-javascript#77]
Functions in the class MoneroUtils require `monero_wallet_keys.wasm` to be pre-loaded even when the superset module is already loaded in the worker context. The solution is to move the execution of MoneroUtils functions into the worker context.

**Comment by woodser** [comment]
This is now supported in v0.7.0.

All utilities in MoneroUtils are now async and run in the worker by default.

You can override running in the worker with `MoneroUtils.setProxyToWorker(false)`.
