### ISSUE TITLE
Library is not responding to 401 authentication challenge when bundled and run in Firefox

### ISSUE THREAD

**Issue by woodser** [monero-ecosystem/monero-javascript#8]
When bundled in a web app (e.g. [xmr-sample-app](https://github.com/woodser/xmr-sample-app)) and run in Firefox, monero-javascript's http client (used in [MoneroRpcConnection.js](https://github.com/monero-ecosystem/monero-javascript/blob/master/src/main/js/rpc/MoneroRpcConnection.js)) does not respond to the server's 401 authentication challenge.

**Comment by trasherdk** [comment]
Okay. I got a little further down the road now. `Firefox 72.0.2 (64-bit)`
Setting up SSL/TLS and reverse proxy on Apache, did help some.
No `CORS` or `Mixed contents` errors.

On first try, I was prompted for username/password by Apache, but further tries not (cached).
```
	ProxyPreserveHost On
	
	ProxyPass /daemon http://xmr-app.fumlersoft.dk:38081
	ProxyPassReverse /daemon http://xmr-app.fumlersoft.dk:38081

	ProxyPass /wallet http://xmr-app.fumlersoft.dk:38083
	ProxyPassReverse /wallet http://xmr-app.fumlersoft.dk:38083

	ProxyPassReverseCookiePath / /
```
And setting up connections in `xmr-sample-app` like this:
```
    const daemon_config = {
      uri: "https://xmr-app.fumlersoft.dk/daemon",
      protocol: "http",
      host: "xmr-app.fumlersoft.dk",
      port: 38081,
      user: login.deamon.user,
      pass: login.deamon.pass
    }

    // connect to monero-daemon-rpc
    console.log("Connecting to monero-daemon-rpc...");

    let daemon = new MoneroDaemonRpc(daemon_config);
```

**Comment by woodser** [comment]
Side note, in the configuration, either a uri or a protocol, host, and port should be used, but not both.  I'm adding a validation check accordingly.

**Comment by trasherdk** [comment]
Yes, the config.uri thing is only for my proxy workaround.

I was wrong about the caching of username/password. I get the challenge on every run.

I get an `401` on this call:
```
{
	"id": "0",
	"jsonrpc": "2.0",
	"method": "open_wallet",
	"params": {
		"filename": "test_wallet_1",
		"password": "supersecretpassword123"
	}
}
```
But the `open_wallet` request seems to succeed anyway.
The following call to `query_key` succeeds.
The following call to `get_accounts` succeeds.
It seems `wallet_worker.js` dies at `Synchronizing core wallet...`

**Comment by woodser** [comment]
I pushed updates to monero-javascript `wasm83_start_syncing` and xmr-sample-app `wasm68_onward` branches to enable background syncing and synchronize access to the wasm module.  Can you please update and see if the problem persists?  What are your browser's network requests doing when it gets to "Synchronizing core wallet..."?  Thanks.

**Comment by trasherdk** [comment]
Your `config.uri` vs `config.protocol/host/port` change seems wrong to me.

In `MoneroRpcConnection` 
```
    // normalize config
    if (typeof config === "string") this.config = {uri: config};
    else {
      if (config.uri) assert(!config.host && !config.protocol && !config.port, "Can specify either uri or protocol, host, and port but not both");
      this.config = Object.assign({}, config);
    }
```
followed by
```
    // delete host and port if uri given
    if (this.config.uri) {
      delete this.config.protocol;
      delete this.config.host;
      delete this.config.port;
    }
```
You could issue a warning saying `uri take precedence over protocol + host + port`or something along those lines.

**Comment by trasherdk** [comment]
With the latest updates `MoneroDaemonRpc` fails silently, resulting in `daemon = undefined`.
```
    const daemon_config = {
//      uri: "http://xmr-app.fumlersoft.dk:38981",
      protocol: "http",
      host: "xmr-app.fumlersoft.dk",
      port: 38081,
      user: login.deamon.user,
      pass: login.deamon.pass
    }

    // connect to monero-daemon-rpc
    console.log("Connecting to monero-daemon-rpc...");
    try {
      let daemon = new MoneroDaemonRpc(daemon_config);
    } catch (e) {
//      console.error(e.message);
      throw e;
    }
```
Both `Firefox` and `Chrome`.

The `open_wallet` request fails with `401` on `Firefox` but succeed on `Chrome`.

This is without reverse proxy.

**Comment by trasherdk** [comment]
Removing the `try {} catch()` around `let daemon = new MoneroDaemonRpc(daemon_config);` makes it complete successfully. I have to manually  enter user/password for daemon and wallet.

Running with reverse proxy I get to `await walletCore.sync(new WalletSyncPrinter());`
No request is sent. No error is given.

Running without reverse proxy I get `401` errors.

**Comment by woodser** [comment]
@trasherdk

What specifically do you think is wrong about the changes to config.uri vs config.protocol, config.host, and config.port?  That it errors if both are provided?  I think the safe thing to do is error if redundant but conflicting config is provided.  It could be permitted if they matched.

I tested initializing MoneroDaemonRpc with config.uri vs config.protocol, config.host, and config.port after the updates and do not observe any difference in behavior.

To clarify, is everything working as expected in Chrome, including synchronizing the core wallet?  In Firefox, new MoneroDaemonRpc() fails silently when wrapped in try...catch and execution stops after walletCore.sync() with a reverse proxy?  Is anything new broken after the update?  Thanks.

**Comment by trasherdk** [comment]
1. The code already deletes config.protocol/host/port if config.uri is provided.
[MoneroRpcConnection#L47](https://github.com/trasherdk/monero-javascript/blob/7a98c3e541d0451cded89f64de0d92833b8f14d1/src/main/js/rpc/MoneroRpcConnection.js#L47))
That was the reason I did it like that.

2. When wrapped in `try {} catch()` both Chrome and Firefox fail silently on `new MoneroDaemonRpc()`
When **NOT** wrapped in `try {} catch()` both Chrome and Firefox succeeds on `new MoneroDaemonRpc()`

3. Firefox, when running reverse-proxy, I get to enter user/password manually.
The last request sent is:   `{"id":"0","jsonrpc":"2.0","method":"get_accounts","params":{}}`
The `await walletCore.sync(new WalletSyncPrinter());` never makes a request.
There's a bunch of this kind of empty requests, with no response:
   ```
   await fetch("http://xmr-app.fumlersoft.dk:0/json_rpc", {
       "credentials": "omit",
       "headers": {},
       "method": "POST",
       "mode": "cors"
   });
   ```

4. Chrome, when running reverse-proxy, I get to enter user/password manually.
The `await walletCore.sync(new WalletSyncPrinter());` results in:
   ```
   Uncaught (in promise) Error: Wallet is not connected to daemon
       at a.sync (MoneroWalletCore.js:501)
       at async runWallet (wallet_worker.js:148)
   i @ MoneroError.js:13
   sync @ MoneroWalletCore.js:501
   async function (async)
   runWallet @ wallet_worker.js:33
   ```
Followed by a bunch of unanswered `get_info` and `get_version` requests.

**Comment by trasherdk** [comment]
Chrome, when sending requests to ports: 38081 and 38083 all is good.
Background synchronizing happily :smile: 

Firefox, when sending requests to ports: 38081 and 38083 all is `401` :sob:

**Comment by trasherdk** [comment]
My internet connection was cycled during the night, and I woke up to:
```
Background synchronizing 
monero-javascript-wasm.js:9 error property exists, returning false
monero-javascript-wasm.js:9 Compiled code throwing an exception, 35532032,11016,120
pi @ monero-javascript-wasm.js:9
e.<computed> @ monero-javascript-wasm.js:9
(anonymous) @ wasm-056a5a8e-9869:1
(anonymous) @ wasm-056a5a8e-6239:1
(anonymous) @ wasm-056a5a8e-2249:1
(anonymous) @ wasm-056a5a8e-8326:1
(anonymous) @ wasm-056a5a8e-4041:1
(anonymous) @ wasm-056a5a8e-16930:1
(anonymous) @ wasm-056a5a8e-4040:1
(anonymous) @ wasm-056a5a8e-26913:1
(anonymous) @ wasm-056a5a8e-8778:1
(anonymous) @ wasm-056a5a8e-8779:1
(anonymous) @ wasm-056a5a8e-11739:1
(anonymous) @ wasm-056a5a8e-2169:1
(anonymous) @ wasm-056a5a8e-11736:1
(anonymous) @ wasm-056a5a8e-17491:1
(anonymous) @ wasm-056a5a8e-11440:1
(anonymous) @ wasm-056a5a8e-14754:1
t.<computed> @ monero-javascript-wasm.js:9
(anonymous) @ monero-javascript-wasm.js:9
(anonymous) @ monero-javascript-wasm.js:9
Promise.catch (async)
(anonymous) @ monero-javascript-wasm.js:9
Promise.then (async)
(anonymous) @ monero-javascript-wasm.js:9
handleSleep @ monero-javascript-wasm.js:9
at @ monero-javascript-wasm.js:9
e.<computed> @ monero-javascript-wasm.js:9
(anonymous) @ wasm-056a5a8e-16930:1
(anonymous) @ wasm-056a5a8e-4040:1
(anonymous) @ wasm-056a5a8e-26913:1
(anonymous) @ wasm-056a5a8e-8778:1
(anonymous) @ wasm-056a5a8e-8779:1
(anonymous) @ wasm-056a5a8e-11739:1
(anonymous) @ wasm-056a5a8e-2169:1
(anonymous) @ wasm-056a5a8e-11736:1
(anonymous) @ wasm-056a5a8e-17491:1
(anonymous) @ wasm-056a5a8e-11440:1
(anonymous) @ wasm-056a5a8e-14754:1
t.<computed> @ monero-javascript-wasm.js:9
c.dynCall_viiii @ monero-javascript-wasm.js:9
i @ monero-javascript-wasm.js:9
(anonymous) @ monero-javascript-wasm.js:9
(anonymous) @ MoneroWalletCore.js:533
(anonymous) @ MoneroWalletCore.js:518
(anonymous) @ MoneroUtils.js:17
(anonymous) @ async.js:4096
process @ async.js:2344
(anonymous) @ async.js:2252
(anonymous) @ async.js:119
(anonymous) @ setImmediate.js:40
f @ setImmediate.js:69
toString.call.e.MessageChannel.port1.onmessage @ setImmediate.js:128
wallet_worker.js:1 Uncaught (in promise) 35532032 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.
Promise.catch (async)
(anonymous) @ monero-javascript-wasm.js:9
Promise.then (async)
(anonymous) @ monero-javascript-wasm.js:9
handleSleep @ monero-javascript-wasm.js:9
at @ monero-javascript-wasm.js:9
e.<computed> @ monero-javascript-wasm.js:9
(anonymous) @ wasm-056a5a8e-16930:1
(anonymous) @ wasm-056a5a8e-4040:1
(anonymous) @ wasm-056a5a8e-26913:1
(anonymous) @ wasm-056a5a8e-8778:1
(anonymous) @ wasm-056a5a8e-8779:1
(anonymous) @ wasm-056a5a8e-11739:1
(anonymous) @ wasm-056a5a8e-2169:1
(anonymous) @ wasm-056a5a8e-11736:1
(anonymous) @ wasm-056a5a8e-17491:1
(anonymous) @ wasm-056a5a8e-11440:1
(anonymous) @ wasm-056a5a8e-14754:1
t.<computed> @ monero-javascript-wasm.js:9
c.dynCall_viiii @ monero-javascript-wasm.js:9
i @ monero-javascript-wasm.js:9
(anonymous) @ monero-javascript-wasm.js:9
(anonymous) @ MoneroWalletCore.js:533
(anonymous) @ MoneroWalletCore.js:518
(anonymous) @ MoneroUtils.js:17
(anonymous) @ async.js:4096
process @ async.js:2344
(anonymous) @ async.js:2252
(anonymous) @ async.js:119
(anonymous) @ setImmediate.js:40
f @ setImmediate.js:69
toString.call.e.MessageChannel.port1.onmessage @ setImmediate.js:128
```

**Comment by trasherdk** [comment]
A functioning example of XMLHttpRequest and Digest Authorization:
[GitHub](https://github.com/trasherdk/digest-request/tree/master/test-02)
[Prof of concept](http://digest-request.fumlersoft.dk/test-02/test.html)

Can something like this be implemented?

**Comment by woodser** [comment]
Documented issue to recover from interrupted background sync: #12

**Comment by trasherdk** [comment]
The `401 Unauthorized` seems to be a bug in Mozilla's realm.

Firefox can't handle the situation where the server return more than one `WWW-Authenticate` header.

[WWW-Authenticate does not return anything, if server sends more than one such header](https://bugzilla.mozilla.org/show_bug.cgi?id=1491010)

**Comment by woodser** [comment]
FYI issue #12 to recover from failed background syncs is resolved.

**Comment by woodser** [comment]
Firefox is now supported using XHR digest authentication in master and [v0.2.11](https://github.com/monero-ecosystem/monero-javascript/releases/tag/v0.2.11) published release.

Please let me know if you see any issues.

**Comment by trasherdk** [comment]
Looks very good. The test ran all the way, and is background syncing.

It looks to me like 3 instances of `MoneroWebWorker.dist.js` is loaded.. Is that so?
I'm assuming only `test_wallet_1` should be open at the end of the test run, right?

**Comment by woodser** [comment]
Good to hear.

> It looks to me like 3 instances of MoneroWebWorker.dist.js is loaded.. Is that so?

It was so.  I've pushed a new release, v0.2.13, which closes all wallets by the end of the test suite and fixes a potential race condition in the tests.

**Comment by trasherdk** [comment]
I'm running with 0.2.13 now... looking good on http. Not looking so good on https.

**Comment by woodser** [comment]
0.2.14 is released to fix https.

For reference, I wrote up a brief guide to enable https with self-signed certificates on localhost:

ENABLE DAEMON AND WALLET RPC SSL
1. `cd /path/to/monero_cli`
2. generate certificates for daemon rpc (set password, use defaults except common name "localhost"): `openssl req -x509 -newkey rsa:4096 -keyout daemon-rpc-key.pem -out daemon-rpc-cert.pem -days 365`
3. generate certificates for wallet rpc (set password, use defaults except common name "localhost"): `openssl req -x509 -newkey rsa:4096 -keyout wallet-rpc-key.pem -out wallet-rpc-cert.pem -days 365`
4. start daemon rpc with ssl and input password: `./monerod --stagenet --rpc-login superuser:abctesting123 --rpc-access-control-origins https://localhost:9100 --rpc-ssl enabled --rpc-ssl-private-key daemon-rpc-key.pem --rpc-ssl-certificate daemon-rpc-cert.pem`
5. start wallet rpc with ssl and input password: `./monero-wallet-rpc --daemon-address https://localhost:38081 --daemon-login superuser:abctesting123 --stagenet --rpc-bind-port 38083 --rpc-login rpc_user:abc123 --wallet-dir ./ --rpc-access-control-origins https://localhost:9100 --rpc-ssl enabled --rpc-ssl-private-key wallet-rpc-key.pem --rpc-ssl-certificate wallet-rpc-cert.pem`

ENABLE NODEJS SSL
1. construct MoneroWalletRpc and MoneroDaemonRpc with rejectUnauthorized: false, change rpc uris to https

ENABLE WEB APP SSL
1. change rpc uris to https
2. generate certificates for localhost web app (set password, use defaults except common name "localhost"): `openssl req -x509 -newkey rsa:4096 -keyout localhost-key.pem -out localhost-cert.pem -days 365`
3. configure run_server.py to use generated certificates
4. test in chrome: chrome://flags/#allow-insecure-localhost, set "Allow invalid certificates for resources loaded from localhost." to Enabled
5. test in firefox: authenticate with https://localhost:38081/json_rpc and https://localhost:38083/json_rpc first, then run https://localhost:9100/

**Comment by woodser** [comment]
Closing this.  Please let me know if you see any further issues in Firefox.

**Comment by easrng** [comment]
I'm getting 401s and monero-javascript isn't sending any authentication.

**Comment by woodser** [comment]
@easrng a 401 authentication challenge is normal and expected for each API call. The subsequent request should succeed with 200.

**Comment by easrng** [comment]
whoops it was actually a CORS error
