### ISSUE TITLE
Connecting to a wallet RPC: Method not found

### ISSUE THREAD

**Issue by YakovL** [monero-ecosystem/monero-javascript#85]
I'm trying to connect Monero wallet RPC (for tests to an open node) based on [docs](https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/creating_wallets.md) and [tests](https://github.com/monero-ecosystem/monero-javascript/blob/master/src/test/TestMoneroWalletRpc.js) and haven't succeeded yet. I've described several attempts [at stackexchange](https://monero.stackexchange.com/q/13550/14510) and here I'll focus on one approach.

I've generated a valid mnemonic ([here](https://xmr.llcoins.net/addresstests.html)), generated keys and address offline and have send some test tokens to the address via [the faucet](https://melo.tools/faucet/testnet/). I'm trying to connect to wallet RPC using a node (currently https://testnet.xmr.ditatompel.com) taken from the [list](https://monero.fail) of public nodes (with this node, I've successfully called [get_block_count](https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#get_block_count) JSON RPC method and [get_transactions](https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#get_transactions) PRC method of Daemon RPC, so it works at least with those). However, I'm not sure if each node supporting Daemon RPC also supports Wallet RPC (please help me clarify that).

Now, here's my attempt in the nutshell:

    const walletRpc = await monerojs.connectToWalletRpc({
        uri: nodeUri, // actually, I've tested all the 4 currently available nodes for testnet, the result is the same for each one
        username: "rpc_user", // not sure how these are managed; tested without username/password as well, same result
        password: "abc123",
    });
    // console.log(walletRpc) shows MoneroWalletRpc with the provided config details and MoneroRpcConnection details
    // console.log(walletRpc.createWallet) and console.log(walletRpc.openWallet) show [AsyncFunction: createWallet] and [AsyncFunction: openWallet] respectively

    // this failes with "Method not found"
    const result = await walletRpc.createWallet({
        // networkType: moneroNetwork,
        mnemonic,
    });

Why `createWallet` fails? Is it supposed to only work with a local node? If there is a way to create a wallet/connect to it using a public node, please help me figure what's wrong with this attempt.

I've also tried

    const res = await walletRpc.openWallet({
        // networkType: moneroNetwork,
        mnemonic,
    });

which fails "Must provide name of wallet to open", so I guess I do have to create the wallet first.

**Comment by woodser** [comment]
`await monerojs.connectToWalletRpc()` expects to connect to a monero-wallet-rpc server which is different from a Monero node / daemon.

Typically people host their own monero-wallet-rpc server which connects to a Monero node to provide self-hosted wallet functionality.

**Comment by woodser** [comment]
Closing as resolved. Please feel free to ask if you have further questions.

**Comment by itsMikeLowrey** [comment]
Does this mean that monerojs.createWalletFull() command also needs to connect to a rpc node not just a public daemon in order to function? And does that mean that all functions that handle specific wallet info needs to connect to a rpc node also?
